### PR TITLE
Update domains.html hook.io IP address

### PR DESCRIPTION
**Pull request by LukeeeeBennett**
Update `domains.html` hook.io IP address from `104.131.118.1` to `159.203.77.62`.

**Currently:**

http://hook.io/domains says `104.131.118.1`.

https://hook.io/docs#domains says `159.203.77.62`.

### CODE REVIEW

**Comment by Marak** [comment]
@LukeeeeBennett -

Good catch. I'm actually seeing `162.243.187.144` as the balancer IP?

Where did `159.203.77.62` come from?

**Comment by LukeeeeBennett** [comment]
`159.203.77.62` came from https://hook.io/docs#domains

Thanks for fixing, will update DNS 😁

**Comment by Marak** [comment]
That's really not great on our end. 

Thank you for finding this and reporting the issue.

I've switched load balancer public IP string in view from hard-coded to using config variable on both `/domains` and `/docs` pages. 

Please let me know if you find any other issues with documentation or project. Thanks again for your contributions.

**Comment by LukeeeeBennett** [comment]
No problem! Amazingly speedy fix, thank you!

**Pull request closed without merging**
