### PR TITLE
Lets make hook.io run smoothly on local machine 

### PR DESCRIPTION
**Pull request by chetandhembre**

### CODE REVIEW

**Comment by Marak** [comment]
@chetandhembre - Nice one!

You'll probably want to use master of `mschema-forms` and `resource-forms`

Can you sign our Contributions License Agreement: https://www.clahub.com/agreements/bigcompany/hook.io ? All contributors are required to sign.

**Comment by chetandhembre** [comment]
@Marak not able to sign contribution license agreement as service is throwing error

**Comment by Marak** [comment]
It's not working? Ping @jasonm

**Comment by Marak** [comment]
@chetandhembre 

We now have a working docker image so you can easily start a local hook.io

Check out the README for more details.

Cheers!

**Pull request closed without merging**
